# Generated by Django 3.1.8 on 2021-04-26 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boat',
            name='hin',
            field=models.CharField(max_length=12, unique=True, verbose_name='HIN'),
        ),
        migrations.AlterField(
            model_name='car',
            name='vin',
            field=models.CharField(max_length=17, unique=True, verbose_name='VIN'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='vin',
            field=models.CharField(max_length=17, unique=True, verbose_name='VIN'),
        ),
    ]
